### ISSUE TITLE
When we hover over the occations navigation in the header then the dots are coming in the preview as it is not coming in the live.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Leleyat-S.O.---April-22nd#1]
**Actual result:** 
When we hover over the occations navigation in the header then the dots are coming in the preview as it is not coming in the live.
![image](https://user-images.githubusercontent.com/102131636/165088181-8770ad89-7f96-4b9f-a48b-294edbe32936.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/102131636/165088278-edd5b8e9-025a-48ec-ba77-89782d4c0c68.png)

**Comment by devabulabbas** [comment]
Resolved 
@sudhanshu0603

**Comment by sudhanshu0603** [comment]
resolved
