### ISSUE TITLE
The arrow is coming in the middle in preview site.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Leleyat-S.O.---April-22nd#2]
**actual result:**
The arrow is coming in the middle in preview site.
![image](https://user-images.githubusercontent.com/102131636/165228176-452fee3c-a1f2-49ea-855b-39c6c8f0d5d4.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/102131636/165228262-ed9293c5-de83-4ecf-b3b4-d5ad99db5a22.png)
The arrow is coming to the  right in live.

**Comment by devabulabbas** [comment]
@sudhanshu0603 
Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
