### ISSUE TITLE
The cross symbol is not coming in preview sometime.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Leleyat-S.O.---April-22nd#3]
**Actual result:**
The cross symbol is not coming in preview sometime.
![image](https://user-images.githubusercontent.com/102131636/165234143-06c5aee1-ebd4-489a-8c99-d1ab2f8aa8bb.png)

**Expected result:** 
![image](https://user-images.githubusercontent.com/102131636/165234279-8ed753e5-7fe8-412d-939b-3f078f37c799.png)

**Comment by devabulabbas** [comment]
@sudhanshu0603 
Resolved

**Comment by sudhanshu0603** [comment]
as it is coming in live also.  no need to resolve it
